apiVersion: apps.kubeflow.org/v1alpha1
kind: Application
metadata:
  name: application
spec:
  app:
    env: default
    modules:
      - name: notebooks
        components:
          - name: jupyter
            prototype: jupyter
          - name: notebooks
            prototype: notebooks
          - name: ambassador
            prototype: ambassador
          - name: centraldashboard
            prototype: centraldashboard
          - name: spartakus
            prototype: spartakus
    parameters:
      - component: ambassador
        name: ambassadorServiceType
        value: LoadBalancer
    packages:
      - name: core
      - registry: kubeflow
    registries:
      - name: kubeflow
        repo: https://github.com/kubeflow/kubeflow.git
        version: master
        # relative path to registry from git repo.
        path: kubeflow
        RegUri: /opt/registries/kubeflow/kubeflow
