# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  # kfctl test runs tests on gke.
  - app_dir: kubeflow/kubeflow/testing/workflows
    component: kfctl_test
    name: kfctl
    job_types:
      - presubmit
      - postsubmit
      - periodic
    include_dirs:
      - scripts/*
      - kubeflow/*
      - testing/*
      - deployment/*
    params:
      platform: gke
      gkeApiVersion: v1
  - app_dir: kubeflow/kubeflow/testing/workflows
    component: kfctl_test
    name: kfctl-beta
    job_types:
      - presubmit
      - postsubmit
      - periodic
    include_dirs:
      - scripts/*
      - kubeflow/*
      - testing/*
      - deployment/*
    params:
      platform: gke
      gkeApiVersion: v1beta1

