# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  # kfctl test runs tests on gke.
  - app_dir: kubeflow/kubeflow/testing/workflows
    component: kfctl_test
    name: kfctl
    job_types:
      - presubmit
      - postsubmit
    include_dirs:
      - scripts/*
      - kubeflow/*
      - testing/*
    params:
      platform: gke
  # Run unittests
  # TODO(jlewi): Need to add step to run go and python unittests
  - app_dir: kubeflow/kubeflow/testing/workflows
    component: unit_tests
    name: unittests    
  # Run tests on GKE
  # TODO(jlewi): We need to refactor this. We don't
  # want to use workflows to run GKE tests anymore
  # we use kfctl_test for that. We need to split
  # workflows into 2 workflows
  # 1. one for unittests like test_jsonnet
  # 2. one for minikube
  # minikube test should only run on presubmit
  # when the test is modified.
  - app_dir: kubeflow/kubeflow/testing/workflows
    component: workflows
    name: kubeflow-e2e-gke
    job_types:
      - presubmit
      - postsubmit
    params:
      platform: gke  
  # Run tests on minikube
  - app_dir: kubeflow/kubeflow/testing/workflows
    component: workflows
    name: kubeflow-e2e-minikube
    job_types:
      - postsubmit
    params:
      platform: minikube
  - app_dir: kubeflow/kubeflow/components/k8s-model-server/images/releaser
    component: workflows
    name: tf-serving-image
    job_types:
      - presubmit
      - postsubmit
    include_dirs:
      - kubeflow/tf-serving/*
      - components/k8s-model-server/*
      - testing/*
