name: kf-test
appconfig:
  registries:
  - name: kubeflow
    repo: https://github.com/kubeflow/kubeflow.git
    version: master
    path: kubeflow
    reguri: /opt/registries/kubeflow/kubeflow
  packages:
  - name: core
    registry: kubeflow
  - name: application
    registry: kubeflow
  components:
  - name: ambassador
    prototype: ambassador
  - name: centraldashboard
    prototype: centraldashboard
  - name: application
    prototype: application
  parameters:
  - component: ambassador
    name: ambassadorServiceType
    value: LoadBalancer
namespace: kubeflow
autoConfigure: false
