apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: kubeflow-kafka-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeflow-kafka-role
subjects:
- kind: ServiceAccount
  name: kubeflow-kafka
