#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/${_REGISTRY}/jupyter-web-app:$TAG_NAME'
    - '--label=git-version=${_GIT_VERSION}'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/${_REGISTRY}/jupyter-web-app:$TAG_NAME'
    - 'gcr.io/${_REGISTRY}/jupyter-web-app:latest'
images: ['gcr.io/${_REGISTRY}/jupyter-web-app:$TAG_NAME',
         'gcr.io/${_REGISTRY}/jupyter-web-app:latest']