# Source: https://github.com/tensorflow/k8s/blob/master/tf-job-operator-chart/templates/service-account.yaml

{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-job-operator
  labels:
    app: tf-job-operator
{{ end }}
