resources:
- manager.yaml
- service-account.yaml

configMapGenerator:
- literals:
  - ADMIN=
  - WORKLOAD_IDENTITY=
  - USERID_HEADER="kubeflow-userid"
  - USERID_PREFIX=
  name: config

images:
- name: docker.io/kubeflownotebookswg/profile-controller
  newName: docker.io/kubeflownotebookswg/profile-controller
  newTag: latest