# Note: the volumes-web-app allows expanding strings using ${VAR_NAME}
# You may use any environment variable. This lets us e.g. specify images that can be modified using kustomize's image transformer.
# Additionally, 'PVC_NAME', 'NAME' and 'NAMESPACE' are defined
podTemplate:
  containers:
    - name: main
      image: $VOLUME_VIEWER_IMAGE
      env:
        - name: FB_ADDRESS
          value: "0.0.0.0"
        - name: FB_PORT
          value: "8080"
        - name: FB_DATABASE
          value: /tmp/filebrowser.db
        - name: FB_NOAUTH
          value: "true"
        - name: FB_BASEURL
          value: /pvcviewers/$NAMESPACE/$NAME/
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 2
        periodSeconds: 10
      volumeMounts:
        - name: pvc
          mountPath: /data
      workingDir: /data
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: $PVC_NAME
service:
  targetPort: 8080
  virtualService:
    basePrefix: "/pvcviewers"
    rewrite: "/"
    timeout: 30s
rwoScheduling:
  enabled: true
  restart: true
