apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfp-conformance
  namespace: kf-conformance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfp-conformance
  template:
    metadata:
      labels:
        app: kfp-conformance
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: kf-conformance
      containers:
      - name: kfp-conformance
      # TODO: update the image version to 1.0
        image: gcr.io/ml-pipeline/kfp-conformance:0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
          requests:
            memory: "64Mi"
            cpu: "0.5"
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/run/secrets/kubeflow/pipelines
          name: volume-kf-pipeline-token
          readOnly: true
        env:
        - name: KF_PIPELINES_SA_TOKEN_PATH
          value: /var/run/secrets/kubeflow/pipelines/token
      volumes:
      - name: volume-kf-pipeline-token
        projected:
          sources:
            - serviceAccountToken:
                path: token
                expirationSeconds: 7200
                audience: pipelines.kubeflow.org
---