resources:
- manager.yaml
- service-account.yaml
- service.yaml
configMapGenerator:
- name: config
  envs:
  - params.env
images:
- name: docker.io/kubeflownotebookswg/notebook-controller
  newName: docker.io/kubeflownotebookswg/notebook-controller
  newTag: latest