apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: configmaps-web-app
        image: public.ecr.aws/j1r0q0g6/notebooks/configmaps-web-app
        ports:
        - containerPort: 5000
        env:
        - name: APP_PREFIX
          value: $(CMWA_PREFIX)
        - name: USERID_HEADER
          value: $(CMWA_USERID_HEADER)
        - name: USERID_PREFIX
          value: $(CMWA_USERID_PREFIX)
      serviceAccountName: service-account
