apiVersion: '0.1'
kind: ksonnet.io/registry
libraries:
  core:
    version: issue_239_ambassador_as_proxy_for_jupyterhub
    path: core
  tf-job:
    version: master
    path: tf-job
  tf-serving:
    version: master
    path: tf-serving
  argo:
    version: master
    path: argo
