# Run a job to build the image from the latest code and then create
# a PR updating the image.
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: jupyter-updater
  generateName: jupyter-updater-
spec:
  template:
    spec:
      initContainers:
      - command:
        - /usr/local/bin/checkout_repos.sh
        # TODO(jlewi): Stop checking out the jlewi fork once it is merged
        - --repos=jlewi/kubeflow@web_app_ci,kubeflow/fairing@HEAD,jlewi/testing@add_hub
        - --src_dir=/src        
        - --links=jlewi/kubeflow=kubeflow/kubeflow
        name: checkout
        image: gcr.io/kubeflow-ci/test-worker:v20190420-70fb4fe-e3b0c4
        volumeMounts:
        - mountPath: /src
          name: src
      containers:
      - command:
        - python3 
        - -m 
        - kubeflow.kubeflow.ci.update_jupyter_web_app
        - all
        - --project=kubeflow-images-public
        image: gcr.io/kubeflow-ci/test-worker:v20190420-70fb4fe-e3b0c4
        name: update
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/key.json
        - name: PYTHONPATH
          value: /src/kubeflow/kubeflow/py:/src/kubeflow/testing/py:/src/kubeflow/fairing        
        volumeMounts:
        - mountPath: /src
          name: src
        - mountPath: /secret/gcp-credentials
          name: gcp-credentials
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: src
        emptyDir: {}
      - name: gcp-credentials
        secret:
          secretName: kubeflow-testing-credentials
