name: Build & Publish all Docker images
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - releasing/version/VERSION
    types:
      - closed

jobs:
  push_to_registry:
    name: Build & Push all Docker images to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build and Push all Kubeflow images
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/
        make build-all
        make push-all
