name: CentralDashboard-Angular Intergration Test
on:
  pull_request:
    paths:
      - components/centraldashboard-angular/**
    branches:
      - master
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMG: centraldashboard-angular
  TAG: intergration-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build CentralDashboard-Angular Image
      run: |
        cd components/centraldashboard-angular
        make docker-build

    - name: Install KinD
      run: ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind-1-25.yaml

    - name: Load Images into KinD Cluster
      run: |
        kind load docker-image ${{env.IMG}}:${{env.TAG}}

    - name: Install kustomize
      run: ./components/testing/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./components/testing/gh-actions/install_istio.sh

    - name: Build & Apply manifests
      run: |
        cd components/centraldashboard-angular/manifests
        kubectl create ns kubeflow

        export CURRENT_CENTRALDB_IMG=docker.io/kubeflownotebookswg/centraldashboard-angular:latest
        export PR_CENTRALDB_IMG=${{env.IMG}}:${{env.TAG}}

        kustomize build overlays/kserve | kubectl apply -f -

        DEPLOYMENT=centraldashboard-angular
        CONTAINER=centraldashboard-angular

        IMG=${{env.IMG}}:${{env.TAG}}
        kubectl patch deployment $DEPLOYMENT -n kubeflow --patch \
          '{"spec": {"template": {"spec": {"containers": [{"name": "'"$CONTAINER"'","image": "'"$IMG"'"}]}}}}'

        kubectl wait deploy -n kubeflow $DEPLOYMENT --for=jsonpath='{.status.readyReplicas}'=1 --timeout=300s
