# This workflow will build and push Docker images and will log in to a Docker registry if required.
# For more information see: https://github.com/docker/build-push-action

name: platiagro-notebook - Build and push Docker image

on:
  push:
    branches: [ v0.2.0-kubeflow-v1.1-branch ]

jobs:
  build-cpu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push notebook image for CPU
      uses: docker/build-push-action@v1
      with:
        path: components/contrib/platiagro-notebook-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        repository: platiagro/platiagro-notebook-image
        tags: 0.2.0
        dockerfile: components/contrib/platiagro-notebook-image/Dockerfile.cpu

    - name: Build and push experiment image for CPU
      uses: docker/build-push-action@v1
      with:
        path: components/contrib/platiagro-notebook-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        repository: platiagro/platiagro-experiment-image
        tags: 0.2.0
        dockerfile: components/contrib/platiagro-notebook-image/Dockerfile.experiment
        build_args: BASE_CONTAINER=platiagro/platiagro-notebook-image:0.2.0

    - name: Build and push deployment image for CPU
      uses: docker/build-push-action@v1
      with:
        path: components/contrib/platiagro-notebook-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        repository: platiagro/platiagro-deployment-image
        tags: 0.2.0
        dockerfile: components/contrib/platiagro-notebook-image/Dockerfile.deployment
        build_args: BASE_CONTAINER=platiagro/platiagro-notebook-image:0.2.0

  build-gpu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push notebook image for GPU
      uses: docker/build-push-action@v1
      with:
        path: components/contrib/platiagro-notebook-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        repository: platiagro/platiagro-notebook-image-gpu
        tags: 0.2.0
        dockerfile: components/contrib/platiagro-notebook-image/Dockerfile.gpu

    - name: Build and push experiment image for GPU
      uses: docker/build-push-action@v1
      with:
        path: components/contrib/platiagro-notebook-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        repository: platiagro/platiagro-experiment-image-gpu
        tags: 0.2.0
        dockerfile: components/contrib/platiagro-notebook-image/Dockerfile.experiment
        build_args: BASE_CONTAINER=platiagro/platiagro-notebook-image-gpu:0.2.0

    - name: Build and push deployment image for GPU
      uses: docker/build-push-action@v1
      with:
        path: components/contrib/platiagro-notebook-image
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.hub.docker.com
        repository: platiagro/platiagro-deployment-image-gpu
        tags: 0.2.0
        dockerfile: components/contrib/platiagro-notebook-image/Dockerfile.deployment
        build_args: BASE_CONTAINER=platiagro/platiagro-notebook-image-gpu:0.2.0
