name: Build Jupyter Pytorch Full Notebook Server Docker images
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter-pytorch-full/**
      - components/example-notebook-servers/jupyter-pytorch/**
      - components/example-notebook-servers/jupyter/**
      - components/example-notebook-servers/base/**
      - releasing/version/VERSION

env:
  REGISTRY: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Notebook Server images
      run: |
        cd components/example-notebook-servers/jupyter-pytorch-full
        make docker-build-cpu docker-build-cuda
