name: Build & Publish Jupyter Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/jupyter/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build Notebook Server images via their Makefile
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        make docker-build -C jupyter TAG=${TAG}
        make docker-build -C jupyter-scipy TAG=${TAG}
        make docker-build-cpu -C jupyter-pytorch TAG=${TAG}
        make docker-build-cuda -C jupyter-pytorch TAG=${TAG}
        make docker-build-cpu -C jupyter-pytorch-full TAG=${TAG}
        make docker-build-cuda -C jupyter-pytorch-full TAG=${TAG}
        make docker-build-cpu -C jupyter-tensorflow TAG=${TAG}
        make docker-build-cuda -C jupyter-tensorflow TAG=${TAG}
        make docker-build-cpu -C jupyter-tensorflow-full TAG=${TAG}
        make docker-build-cuda -C jupyter-tensorflow-full TAG=${TAG}
    
    - name: Push Notebook Server images via their Makefile
      if: github.event_name == 'push'
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        REGISTRY ?= kubeflownotebookswg
        for img in jupyter jupyter-scipy jupyter-pytorch-full jupyter-pytorch-cuda-full jupyter-tensorflow-full \
        jupyter-tensorflow-cuda-full ; do \
            docker tag ${img}:${TAG} ${REGISTRY}/${img}:${TAG} ; \
            docker push ${REGISTRY}/${img}:${TAG} ; \
        done
