name: NPM check code format
on:
  pull_request:
    branches:
      - master
    paths:
      - components/crud-web-apps/jupyter/frontend/**

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - name: Install npm and check format
      run: npm format:check
