name: Build & Publish PodDefaults Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/admission-webhook/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run PodDefaults build and push
      run: |
        cd components/admission-webhook
        export IMG=docker.io/kubeflownotebookswg
        make docker-build && make docker-push
