name: Build & Publish PodDefaults Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/admission-webhook/**
    types:
      - closed

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run PodDefaults build
      run: |
        cd components/admission-webhook
        export IMG=kubeflownotebookswg/poddefaults-webhook
        make docker-build

    - name: Run PodDefaults push
      run: |
        cd components/admission-webhook
        export IMG=kubeflownotebookswg/poddefaults-webhook
        make docker-push
