name: Build & Publish Tensorboard Controller Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/tensorboard-controller/**
    types:
      - closed

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run Tensorboard Controller build
      run: |
        cd components/tensorboard-controller
        export IMG=kubeflownotebookswg/tensorboard-controller
        make docker-build

    - name: Run Tensorboard Controller push
      run: |
        cd components/tensorboard-controller
        export IMG=kubeflownotebookswg/tensorboard-controller
        make docker-push
