name: Build & Publish VWA Docker image
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**
    types:
      - closed

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run VWA build
      run: |
        cd components/crud-web-apps/volumes
        export IMG=kubeflownotebookswg/volumes-web-app
        make docker-build

    - name: Run VWA push
      run: |
        cd components/crud-web-apps/volumes
        export IMG=kubeflownotebookswg/volumes-web-app
        make docker-push
