apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namePrefix: secrets-web-app-
namespace: kubeflow
commonLabels:
  app: secrets-web-app
  kustomize.component: secrets-web-app
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/secrets-web-app
  newName: public.ecr.aws/j1r0q0g6/notebooks/secrets-web-app
  newTag: v1.5.0-rc.2
# We need the name to be unique without the suffix because the original name is what
# gets used with patches
configMapGenerator:
- envs:
  - params.env
  name: parameters
vars:
- fieldref:
    fieldPath: data.SWA_CLUSTER_DOMAIN
  name: SWA_CLUSTER_DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: metadata.namespace
  name: SWA_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: service
- fieldref:
    fieldPath: data.SWA_USERID_HEADER
  name: SWA_USERID_HEADER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.SWA_USERID_PREFIX
  name: SWA_USERID_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.SWA_PREFIX
  name: SWA_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
