apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  labels:
    ksonnet.io/component: ingress
  name: letsencrypt
  namespace: default
spec:
  acme:
    dns01:
      providers:
      - clouddns:
          project: kubeflow-dns
          serviceAccountSecretRef:
            key: gcp-sa.json
            name: gcp-sa
        name: prod-dns
    email: jlewi@google.com
    privateKeySecretRef:
      name: letsencrypt-issuer
    server: https://acme-v02.api.letsencrypt.org/directory
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  labels:
    ksonnet.io/component: ingress
  name: staging-gcp-deploy-tls
  namespace: default
spec:
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - staging-deploy.kubeflow.dev
  commonName: staging-deploy.kubeflow.dev
  dnsNames:
  - staging-deploy.kubeflow.dev
  issuerRef:
    name: letsencrypt
  secretName: staging-gcp-deploy-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: staging-deploy.kubeflow.dev
    kubernetes.io/tls-acme: "true"
  labels:
    ksonnet.io/component: ingress
  name: staging-gcp-deploy
  namespace: default
spec:
  backend:
    serviceName: kubeflow-controller
    servicePort: 3000
  rules:
  - http:
      paths:
      - backend:
          serviceName: kubeflow-controller
          servicePort: 8080
        path: /kfctl/*
  tls:
  - hosts:
    - staging-deploy.kubeflow.dev
    secretName: staging-gcp-deploy-tls
