{{- if .Values.jupyterhub.enabled }}
{{- if .Values.rbac.install }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: edit-pod
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: edit-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: edit-pod
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
